name: rss_readneed
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

#  https://pub.dartlang.org
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
#  xml2json:
  gbk2utf8:
#  https://pub.dev/packages/webview_flutter#-readme-tab-
  webview_flutter:
  loading:
  rxdart:
#  本地存储 - 小数据
  shared_preferences: ^0.5.3+4
#  月份选择
  month_picker_dialog: ^0.2.0
#  瀑布流
  flutter_staggered_grid_view: ^0.3.0
  fish_redux:
  flutter_redux: ^0.6.0 #引入新的状态共享库 https://pub.flutter-io.cn/packages/flutter_redux#-readme-tab-
#  加载更多/刷新
  flutter_easyrefresh: ^1.2.7
#  混合开发
#  flutter_boost:
#    git:
#      url: 'https://github.com/alibaba/flutter_boost.git'
#      ref: '1.12.13'
#  相机相册 - video先去除：https://pub.dev/packages/image_picker#-readme-tab-
  image_picker: ^0.6.3+4
#  video_player: ^0.10.8+1
#  存储 https://pub.dev/packages/flutter_cache_manager#-readme-tab-
#  flutter_cache_manager: ^1.1.3
#  加载图片 https://pub.dev/packages/cached_network_image#-readme-tab-
  cached_network_image: ^2.0.0
#  *** https://github.com/flutterchina/dio/blob/master/README-ZH.md ***
  dio:
#  轮播图 https://pub.dev/packages/flutter_swiper#-readme-tab-
#  https://github.com/best-flutter/flutter_swiper/blob/master/README-ZH.md
  flutter_swiper: ^1.1.6
#  序列化 指令(flutter packages pub run build_runner watch) https://github.com/dart-lang/json_serializable
#  https://flutterchina.club/json/#在项目中设置json_serializable
  json_annotation:
#  json转dart 配合 json_annotation https://blog.csdn.net/laxian2009/article/details/83594253
#  j2e -j 'json' -o lib/Weibo -s  =>  flutter packages pub run build_runner build --delete-conflicting-outputs
  json2entity:
#  利用注解实现的路由 https://github.com/alibaba-flutter/annotation_route  与 json_annotation 一起使用时报错？todo:
#  annotation_route:
#  source_gen:

#  也是路由的一种配置，有空看看 todo:
#  fluro:

dev_dependencies:
  flutter_test:
    sdk: flutter
#  序列化
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

#添加资源 ->
  assets:
  - images_assets/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
